server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.koreaIT.webProjectMuk.vo\
google:
  auth:
    url: https://oauth2.googleapis.com
  login:
    url: https://accounts.google.com
  redirect:
    url: http://localhost:8080/login/oauth_google_check
  client:
    id: 1085307948053-eomnkhsbc8091e1e2jql8hfkj3bo4sfl.apps.googleusercontent.com
  secret: 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